// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RmvS91Xl_Ejube35WRGwGkD7yz79J_Q',
    appId: '1:276529399832:web:8afc53c91bbedb7d951b6d',
    messagingSenderId: '276529399832',
    projectId: 'yame-pointe-noire-ab112',
    authDomain: 'yame-pointe-noire-ab112.firebaseapp.com',
    storageBucket: 'yame-pointe-noire-ab112.firebasestorage.app',
    measurementId: 'G-1ZETK5N4T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsrc_6wmyN31h9Y6z5uyJHc-QzzUiYLY',
    appId: '1:276529399832:android:43ea3468cfe13968951b6d',
    messagingSenderId: '276529399832',
    projectId: 'yame-pointe-noire-ab112',
    storageBucket: 'yame-pointe-noire-ab112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdw1wAduQJYpOA0aG3LIx7ohE3FAM9SU',
    appId: '1:276529399832:ios:f62e9ea5242f8197951b6d',
    messagingSenderId: '276529399832',
    projectId: 'yame-pointe-noire-ab112',
    storageBucket: 'yame-pointe-noire-ab112.firebasestorage.app',
    iosBundleId: 'com.yame.yame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkdw1wAduQJYpOA0aG3LIx7ohE3FAM9SU',
    appId: '1:276529399832:ios:f62e9ea5242f8197951b6d',
    messagingSenderId: '276529399832',
    projectId: 'yame-pointe-noire-ab112',
    storageBucket: 'yame-pointe-noire-ab112.firebasestorage.app',
    iosBundleId: 'com.yame.yame',
  );
}
